### ISSUE TITLE
html 不支持热更新，二级page下scss不会生效

### ISSUE THREAD

**Issue by GOD-C** [WangZhenHao/webpack-multiple-page#1]

**Comment by WangZhenHao** [comment]
修改html模板需要手动刷新（模板是很少修改的，不自动刷新问题不大）。二级页面为什么不生效是因为你的js没有import页面中的scss文件

**Comment by moonhx** [comment]
请问下，修改 footer.html里面的内容，手动刷新页面也不会发生变化

**Comment by WangZhenHao** [comment]
> 



> 请问下，修改 footer.html里面的内容，手动刷新页面也不会发生变化

这个算是一个bug了，引入的这些footer.html，没有被webpack检测这些文件的修改。只有修改当前主页面的html文件，webpack就可以顺带更新在主页面引入的那些footer.html子页面了

**Comment by moonhx** [comment]
哦哦，谢了，那我每次保存下主页面

**Comment by moonhx** [comment]
> 哦哦，谢了，那我每次保存下主页面



> > 
> 
> > 请问下，修改 footer.html里面的内容，手动刷新页面也不会发生变化
> 
> 这个算是一个bug了，引入的这些footer.html，没有被webpack检测这些文件的修改。只有修改当前主页面的html文件，webpack就可以顺带更新在主页面引入的那些footer.html子页面了

哦哦，谢了，那我每次保存下主页面
