### ISSUE TITLE
二级page下js路径调用好像有问题

### ISSUE THREAD

**Issue by geekmakersun** [WangZhenHao/webpack-multiple-page#2]
我的pages.js里是这样写的
![1631150123(1)](https://user-images.githubusercontent.com/20056211/132606114-9cececf2-9429-4314-85af-17d4c713d0b2.png)
但是dev显示js 404
![1631150282(1)](https://user-images.githubusercontent.com/20056211/132606273-d48f1c77-b2eb-4daf-8e89-98a98f7f6a94.png)

变成了根据上级路径的了
![image](https://user-images.githubusercontent.com/20056211/132606328-4c9aa24d-77d2-48d1-8460-74b77b80ab41.png)

**Comment by WangZhenHao** [comment]
[fix] bug  dev模式下，js路径引入错误的问题
